version: '3'
services:
  app:
    image: node:latest
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    volumes:
      - ./docker/storage/mongo:/data/db
